### ISSUE TITLE
'exclude headers'

### ISSUE THREAD

**Issue by jvance325** [klattimer/LGWebOSRemote#12]
#1 I just started with a brand new Ubuntu 16.04 VM and followed your instructions to perfectly. I am using Pythong 2.7.12. When executing python lgtv.py auth "IP Address," I am receiving this same error message. Can you point me in the correct direct in order to resolve it?

**Comment by klattimer** [comment]
closing this as you have failed to install ws4py and spammed already closed issues without reading the comments, or the readme.
