### ISSUE TITLE
`lgtv MyTV on ssl` command not working? (wakeonlan works when given an ip)

### ISSUE THREAD

**Issue by Shasoosh** [klattimer/LGWebOSRemote#124]
* Tested on 42" C2

`lgtv MyTV off ssl`  is working fine. I've tracked down this [issue](https://github.com/klattimer/LGWebOSRemote/issues/110) which resolves to a problem with `getmac` but that's not my issue. My mac address is fine and `config.json` is also configured correctly with the right mac and ip.

On Windows LGTVCompanion works fine.

Calling from the terminal to
`wakeonlan a2:a1:33:42:h2:4g` - doesn't work
`wakeonlan -i 192.168.1.186 a2:a1:33:42:h2:4g` - works!

Any help would be appreciated.

**Comment by klattimer** [comment]
Do you have multiple network adapters?

**Comment by Shasoosh** [comment]
Hey, thanks for the reply.
No. The TV is connected by wifi btw.

**Comment by Shasoosh** [comment]
Sorry, reading your comment again, I guess that Access points qualifies as network adapters.
If that's the case, is there a way to configure it in LGWebOSRemote?

**Comment by Luckyman76489** [comment]
I had a siliar issue, my TV was on a different VLAN. wakeonlan with mac wasn't working but wakeonlan with ip and mac was working as stated above.

I managed to fix the issue by modifying the remote.py script and changed the send_magic_packet function to as follows:

send_magic_packet(self.__macAddress, ip_address=self.__ip)

Hope that helps someone

**Comment by Shasoosh** [comment]
Thanks @Luckyman76489, That's exactly what I ended up doing a few months back.
It would be great if this could be added as a configuration.

**Comment by klattimer** [comment]
@Luckyman76489 make it a PR and I'll pull it in.

**Comment by Luckyman76489** [comment]
@klattimer will do, I've been looking for an excuse to make my first ever PR
