### ISSUE TITLE
Add default options

### ISSUE THREAD

**Issue by xf-** [klattimer/LGWebOSRemote#135]
Would love to see a default option to avoid `-n tv`, ` --name TV` and `--ssl`. 

**Ideas**
If I auth with SSL it will be set on every command to that device.

**Can be changed via config and a default option**
```
# somthing like this
lgtv config -n tv set ssl on
lgtv config -n tv set ssl off
lgtv config set default tv # will be used in case `-n` is not supplied
```

Most people properly have a single TV or at least a main TV. If you want to avoid options, a standard name like default could be also be a fallback. I prefer a setting.

**Comment by klattimer** [comment]
I think that we need to have a try SSL first, and fail over to plain. The security conscious would thank us for it.
