### ISSUE TITLE
KeyError "MyTV"

### ISSUE THREAD

**Issue by Bobby4Life** [klattimer/LGWebOSRemote#142]
Hi there, 

need help with LG C2 connected to a Mac mini. Followed the instructions and when typing in any command I get the following KeyError:

"bobbys@Mac-mini-from-Bobby ~ % lgtv --name MyTV --ssl swInfo 
Traceback (most recent call last):
  File "/Users/bobbys/.local/bin/lgtv", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/bobbys/Library/Application Support/pipx/venvs/lgtv/lib/python3.12/site-packages/LGTV/__init__.py", line 184, in main
    ws = LGTVRemote(name, **config[name], ssl=args.ssl)
                            ~~~~~~^^^^^^
KeyError: 'MyTV'
bobbyss@Mac-mini-from-Bobby ~ % "

**Comment by Tenzer** [comment]
"MyTV" is only shown as an example. You should use whichever name you specified for the `lgtv auth` command. You can also check the name in the configuration file that likely was written to `~/.lgtv/config.json` in case you can't recall.

**Comment by klattimer** [comment]
@Tenzer for for usability purposes, catching this error and spaffing out something more meaningful is probably a good idea.
