### ISSUE TITLE
In which way i can use the "auth" command??

### ISSUE THREAD

**Issue by Albenzo-Show** [klattimer/LGWebOSRemote#16]
i'm trying to control my tv, but command "auth" don't work. (i try "python lgtv.py auth" or "python lgtv.py auth ipaddress", or create the json file manually, but nothing)

**Comment by klattimer** [comment]
Turn the TV on, then do a scan, if the TV doesn't show up it's probably not compatible.

python lgtv.py scan 
python lgtv.py auth x.x.x.x

**Comment by klattimer** [comment]
Scan times out on certain network routers, so your mileage may vary. Auth will work if you know the IP.
