### ISSUE TITLE
How can I start with the tool? (scan and on)

### ISSUE THREAD

**Issue by flamingteeth** [klattimer/LGWebOSRemote#17]
Hi Klattimer, thanks for providing this tool for us.
After the installation, I assume that I need to do a scan before I can use all the feature. However, when I try SCAN or ON function, I got an error from the python code. (I am new to HA and python...)

pi@hassbian:~/LGTVControl/LGWebOSRemote-master $ python lgtv.py scan
  File "lgtv.py", line 3
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file

pi@hassbian:~/LGTVControl/LGWebOSRemote-master $ python lgtv.py on
  File "lgtv.py", line 3
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file

N.B. my TV is LG 65FL6350, it is a WebOS 2.0 TV. I have set a static IP for the TV, and enabled the LG Connect APP feature from the setting. 

Thanks a lot for this.

**Comment by klattimer** [comment]
Fixed. Sorry my bad.

**Comment by klattimer** [comment]
This does not work on webos 2.0 only 3.0+ YMMV
