### ISSUE TITLE
Should be able to name TVs and have multiple TVs

### ISSUE THREAD

**Issue by klattimer** [klattimer/LGWebOSRemote#21]
Looks like I overlooked having more than one LGTV, will work on that later.

**Comment by zhdenny** [comment]
Would love to see support for TV-specific commands...I have multiple LG Televisions in my household I would like to individually control

**Comment by gaitskell** [comment]
This would be very useful - multiple LG TVs in office meeting rooms and it would be very useful to access them all from single commands. Any chance of adding it? Thanks,

**Comment by klattimer** [comment]
0.2 deals with this
