### ISSUE TITLE
Notification message sentence

### ISSUE THREAD

**Issue by kallund** [klattimer/LGWebOSRemote#24]
How do you use the the notification command to send a sentence to the tv?

This works for one word: 
lgtv.sh notification test
Or this: lgtv.sh notification test_test_test

Tried using quotes or double quotes. But it dont work when I use blank space or special characters, example åäö in my language.

Otherwise it works great! I think my lack of knowledge is the problem. Thanks.

**Comment by krzysiek-007** [comment]
python lgtv.py notification 'tray this instruction '

**Comment by krzysiek-007** [comment]
Good work in 50UJ701V

**Comment by kallund** [comment]
Thanks! The problem was the interpreter to be used when running the python script from a switch in domoticz and a permission issue.
