### ISSUE TITLE
Is there a command to open the web browser full screen?

### ISSUE THREAD

**Issue by gabe-sorensen** [klattimer/LGWebOSRemote#26]
I am thinking of using this in some sort of kiosk setup, and was wondering if there's a way to enter and exit full screen with this?

**Comment by klattimer** [comment]
Do you know what the button code is for fullscreen? Basically each command is added more or less here;
https://github.com/klattimer/LGWebOSRemote/blob/2ca4c2cb2d8a023a29e67aaab8ddc5aa60f2c810/LGTV/__init__.py#L304

It's fairly simple to play around and test some button codes, for instance you might try adding the lines 

    def fullscreen(self, fullscreen=True, callback=None):
        self.__send_command("", "request", "ssap://com.webos.service.tv.display/fullscreen", {"fullscreen": fullscreen}, callback)

or maybe it's as simple as editing the openBrowserAt by adding fullscreen as a parameter in __send_command? 

I haven't really got time to experiment with this right now so best of luck if you figure it out file a pull request.

**Comment by balcsida** [comment]
I tried every button on my remote, but none of them puts my LG TV's browser to full screen.
I will try if the above command will work, however, I already tried the "extra parameter" way and it did not work.

**Comment by balcsida** [comment]
I downloaded the SDK with the emulator, and I will try to disassemble it, if possible.

**Comment by septikos** [comment]
balscida, hey any luck with fullscreen?

**Comment by balcsida** [comment]
No, I did not have any luck, unfortunately.

**Comment by odelma** [comment]
If you are looking for any usable workaround for launching the browser to full screen, please check: https://github.com/hobbyquaker/lgtv2/issues/23#issuecomment-450331073

That did the trick for me...:smile:

**Comment by septikos** [comment]
damn, nice hack will try it, thanks!

**Comment by gabe-sorensen** [comment]
Looks like that workaround should work for me. Thanks
