### ISSUE TITLE
Install Tool in Windows

### ISSUE THREAD

**Issue by testpop1901** [klattimer/LGWebOSRemote#31]
HI
Can you share the setup to install this tool in Windows 10

**Comment by klattimer** [comment]
I don't use python on windows 10 so I have no way of providing what you ask for. I'll leave the issue open however someone else will have to fix it.

**Comment by DarkCeptor44** [comment]
Hello @testpop1901, if you still want to know you can install it on Windows 10 by first installing Python (3+) then running the command `pip install git+https://github.com/klattimer/LGWebOSRemote`, that's it!

**Comment by ckorodenis** [comment]
I tried the above procedure, but without success. I use Win10-64bit and I have Python 3.9.0 installed ... I would like to use the script you created to turn the TV on and off. Would that somehow invent?

**Comment by ckorodenis** [comment]
Theoretically, a script executable on Win10 would be enough for me to turn off the TV, I have to turn on the TV with WakeOnLan

**Comment by caue-santos** [comment]
@ckorodenis try wsl2 in Win10:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by klattimer** [comment]
There's a recently included patch which makes the Mac address collection work on windows without using arp. So this is effectively closed.
