### ISSUE TITLE
Youtube does not start with URL/ID

### ISSUE THREAD

**Issue by jonofe** [klattimer/LGWebOSRemote#33]
I don't get the two commands

- openYoutubeURL
- openYoutubeId

to work properly. Youtube is started, but not the video.
I'm using it on WebOS 3.5 (LG55UK6100PLB)

Any advice what is causing this problem and how to resolve?

Here is the log:

```
python lgtv.py openYoutubeId vOW0i8wopaE
{"type": "response", "id": "0", "payload": {"sessionId": "eW91dHViZS5sZWFuYmFjay52NA==", "id": "youtube.leanback.v4", "returnValue": true}}
{"closing": {"reason": "", "code": 1000}}

```

**Comment by klattimer** [comment]
Update to webOS 4 - webOS 3 is not supported.
