### ISSUE TITLE
Problem with send more than 1 word in notification

### ISSUE THREAD

**Issue by vincencique** [klattimer/LGWebOSRemote#34]
I have problem with send notification with spaces (more than 1 word).

This is the result:
root@rpi2:/var/log# /var/www/nettemp/LGWebOSRemote/lgtv.sh notification "Test Test"
Error: Argument lengths do not match
LGTV Controller
Author: Karl Lattimer <karl@qdh.org.uk>
Usage: lgtv <command> [parameter]

Available Commands:
  scan
  auth                  Hostname/IP    Authenticate and exit, creates initial config ~/.lgtv. json
  audioStatus
  audioVolume
  closeApp              appid
  getTVChannel
  input3DOff
  input3DOn
  inputChannelDown
  inputChannelUp
  inputMediaFastForward
  inputMediaPause
  inputMediaPlay
  inputMediaRewind
  inputMediaStop
  listApps
  listChannels
  listInputs
  listServices
  mute                  muted
  notification          message
  off
  on
  openAppWithPayload    payload
  openBrowserAt         url
  openYoutubeId         videoid
  openYoutubeURL        url
  setInput              input_id
  setTVChannel          channel
  setVolume             level
  startApp              appid
  swInfo
  volumeDown
  volumeUp
Traceback (most recent call last):
  File "lgtv.py", line 87, in <module>
    ws.exec_command(sys.argv[1], args)
NameError: name 'args' is not defined

**Comment by klattimer** [comment]
Added a fix to lgtv.sh - thank you for finding this bug.
