### ISSUE TITLE
Closing Web Browser Doesn't Work

### ISSUE THREAD

**Issue by beltsonata** [klattimer/LGWebOSRemote#4]
When I have loaded the webbrowser with openBrowserAt (to http://google.com), and then I do 

`python lgtv.py closeApp com.webos.app.browser`

I get:

> {"payload": {}, "type": "error", "id": "0", "error": "403 access denied"}
> {"payload": {}, "type": "error", "id": "0", "error": "403 access denied"}
> {"closing": {"reason": "", "code": 1000}}

and the TV starts displaying a screensaver. Any ideas why? I can't find a reliable way to close it. Any suggestions would be great.

**Comment by klattimer** [comment]
I'd suggest that LG fucked something up with their API, the reasoning for this is that the remote control code is actually pretty straight forward and not at all going to behave in different ways for different commands.. unless they've changed the command from close to closeapp or something the relevant line of code is this https://github.com/klattimer/LGWebOSRemote/blob/master/lgtv.py#L384. I don't think LG have a bug tracker... If they have a username on here that *might* be a place to start.

**Comment by klattimer** [comment]
I'm going to leave this open until someone either confirms it, or manages to get the original reporter to get theirs working. I expect it's a problem with the TV firmware.

**Comment by beltsonata** [comment]
To be honest, this was on a development LG, so it's likely it's poorly implemented and/or an unfinished build. Many thanks for the response.

**Comment by klattimer** [comment]
Closing as it looks like the OP wasn't using an upto date firmware
