### ISSUE TITLE
arp command deprecated - use ip neigh command instead

### ISSUE THREAD

**Issue by OH1KK** [klattimer/LGWebOSRemote#40]
arp command is deprecated on Debian 9.6. Replacement command to get mac addresses is **ip neigh show**

Here modified  getMacAddress

```
def getMacAddress(address):
    pid = subprocess.Popen(["ip", "neigh", "show", address], stdout=subprocess.PIPE)
    s = pid.communicate()[0].decode('utf-8')
    matches = re.search("(([a-f\d]{1,2}\:){5}[a-f\d]{1,2}) REACHABLE", s)
    if not matches:
        return None
    mac = matches.groups()[0]
    m = mac.split(':')
    mac = ':'.join(['%02x' % int(x, 16) for x in m])
    return mac
```

**Comment by klattimer** [comment]
Could you make a pull request where either it fails over from one to the other method, or knows more about the system before trying?

**Comment by OH1KK** [comment]
After looking closer, I found that I was wrong at first place and this ticked is invalid. There is arp command in Debian, after net-tools package is installed. Arp utility is located /usr/sbin/arp . On debian 9.6 normal user search PATH does not contain /usr/sbin and that's reason why arp command was not found. So if arp is not found, debian user needs to just modify search path.

`export PATH=$PATH:/usr/sbin`

There is no need to alter LGWebOSRemote code.

**Comment by C0rn3j** [comment]
Reopen the issue please, not supporting `iproute2` is an Issue, I don't want `net-tools` installed on my system.
