### ISSUE TITLE
Problem when calling lgtv.sh from child process in node.js

### ISSUE THREAD

**Issue by blefjell** [klattimer/LGWebOSRemote#42]
Hi and thanks for your great libary!
I have succesfully installed it on my pi and I can controll the TV from a command line.
I am trying to integrate it into my HAP-Node.js, so I can for example turn on my TV. To do this I call lgtv.sh as a child process with exec('/home/pi/LGWebOSRemote/lgtv.sh on');
Unfortunately I get this error:
stdout: 
stderr: Traceback (most recent call last):
  File "lgtv.py", line 87, in <module>
    ws = LGTVClient()
  File "/home/pi/LGWebOSRemote/LGTV/__init__.py", line 217, in __init__
    super(LGTVClient, self).__init__('ws://' + self.__hostname + ':3000/', exclude_headers=["Origin"])
TypeError: cannot concatenate 'str' and 'NoneType' objects

exec error: Error: Command failed: /home/pi/LGWebOSRemote/lgtv.sh inputChannelDown
Traceback (most recent call last):
  File "lgtv.py", line 87, in <module>
    ws = LGTVClient()
  File "/home/pi/LGWebOSRemote/LGTV/__init__.py", line 217, in __init__
    super(LGTVClient, self).__init__('ws://' + self.__hostname + ':3000/', exclude_headers=["Origin"])
TypeError: cannot concatenate 'str' and 'NoneType' objects

Can you give any advice on this?
Thanks in advance!

**Comment by klattimer** [comment]
Yeah, it seems that it can't find the config file and load it correctly.

**Comment by wnf58** [comment]
In your  HAP-Node.js you are not the same user as in command line.

LGTVClient load the config file from home path of the user:

class LGTVClient(WebSocketClient):
    def __init__(self, hostname=None):
        self.__command_count = 0
        self.__waiting_callback = None
        if os.path.exists(os.path.expanduser("~/.lgtv.json")):
            f = open(os.path.expanduser("~/.lgtv.json"))
            settings = json.loads(f.read())
            f.close()

**Comment by blefjell** [comment]
I made it work.
I noticed, that I run HAP-Node.js as sudo, so I reran auth with sudo and now it works :)
Thanks for your advice!
