### ISSUE TITLE
LG OLED55C9 mostly working, but queries broken?

### ISSUE THREAD

**Issue by sludtke42** [klattimer/LGWebOSRemote#53]
I'm playing with master, and it looks like you're working on it, so my issue may just be due to living on the bleeding edge. Seems like the package is Python 3 now among other things. Anyway, before I start, thanks for putting this together, exactly what I was looking for!

So, I'm using it with an LG OLED55C9 with WebOS 4.7.0. Installed using Python 3.4, which worked well, except for wakeonlan which I had to install manually. After looking at the source a bit, I managed to figure out the new syntax requiring the device name, and authenticated. Basic commands work fine, on/off/mute/volume. None of the commands for retrieving information seem to work though, eg:

pi$  lgtv LGOLED listInputs
{"closing": {"code": 1000, "reason": ""}}

My only goal here is to be able to turn on the TV and switch inputs, but I can't figure out the correct input names, so I'm stuck. I've tried the input names, like:

pi$  lgtv LGOLED setInput "HDMI 2"
{"closing": {"reason": "", "code": 1000}}

and also the names I assigned to the various inputs, but nothing seems to work.

Any idea?

Thanks again!

**Comment by klattimer** [comment]
Python 2 dies soon, so yes I moved to python 3. 

Sorry I haven't updated the documentation completely yet, I did a lot of work in 1 day and ran out of time. 

Turning the TV on is a ballache sometimes, wake on lan doesn't always work. 

Other than that I've had a dig inside the code and there is a problem receiving responses from the commands, not sure where in the chain it's happening but I suspect ws4py is sending an Origin header and the TV really doesn't like that, I'll take a look as soon as I get time.

**Comment by sludtke42** [comment]
When I check out master, I rarely expect up to date docs  :^)

I did a little digging following your suspicion, and unless I'm really missing something you are suppressing the origin header correctly. Seems like it must be something else. I tried a couple of other things but no luck.

Are the url's you're using for the individual commands actually documented somewhere? I did some digging on the web, but only seem to be able to find the WebOS API. Anyway, no rush. If there's anything I can do to help debug just let me know.

cheers

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by da3dsoul** [comment]
I figured out more about this issue. We are closing the websocket prematurely. If I step through more slowly or thread sleep before closing the connection, then it succeeds. The way this project handles websockets seems to be odd at best.

To answer your immediate issue, HDMI_1 etc is what you want. No spaces, instead underscore.
I have an OLED65B9PUA, and this is its response (beautified):
```
{
  "type": "response",
  "id": "input_0",
  "payload": {
    "returnValue": true,
    "devices": [
      {
        "id": "AV_1",
        "label": "AV",
        "port": 1,
        "connected": false,
        "appId": "com.webos.app.externalinput.av1",
        "icon": "http://15.129.1.98:3000/resources/6868bcd250b05eab17c031f78950c1c35eb5e9e6/av.png",
        "modified": false,
        "subList": [],
        "subCount": 0,
        "favorite": false
      },
      {
        "id": "HDMI_1",
        "label": "THE-THRONE",
        "port": 1,
        "connected": true,
        "appId": "com.webos.app.hdmi1",
        "icon": "http://15.129.1.98:3000/resources/4057cf0526c1f5da08725218186baf330d5c6f6b/pc.png",
        "modified": true,
        "lastUniqueId": 255,
        "hdmiPlugIn": true,
        "dongleConnected": false,
        "subList": [],
        "subCount": 0,
        "favorite": false
      },
      {
        "id": "HDMI_2",
        "label": "THE-POWERHOUSE",
        "port": 2,
        "connected": true,
        "appId": "com.webos.app.hdmi2",
        "icon": "http://15.129.1.98:3000/resources/4057cf0526c1f5da08725218186baf330d5c6f6b/pc.png",
        "modified": true,
        "lastUniqueId": 255,
        "hdmiPlugIn": true,
        "dongleConnected": false,
        "subList": [
          {
            "id": "URCU",
            "serviceType": "audio",
            "connectedInput": "ARC",
            "serviceName": "",
            "settopCode": "incomplete",
            "settopOption": "",
            "brandName": "Denon",
            "labelName": "Denon",
            "codeset": "R3642",
            "ossSetupStatus": "complete",
            "detectedMethod": "auto_lookup",
            "serviceArea": "",
            "isMainSTB": false
          }
        ],
        "subCount": 1,
        "favorite": false
      },
      {
        "id": "HDMI_3",
        "label": "HDMI 3",
        "port": 3,
        "connected": false,
        "appId": "com.webos.app.hdmi3",
        "icon": "http://15.129.1.98:3000/resources/8877fe4f72a79832f2bb32602042d55131a0d5d8/HDMI_3.png",
        "modified": false,
        "lastUniqueId": 255,
        "hdmiPlugIn": false,
        "dongleConnected": false,
        "subList": [],
        "subCount": 0,
        "favorite": false
      },
      {
        "id": "HDMI_4",
        "label": "HDMI 4",
        "port": 4,
        "connected": false,
        "appId": "com.webos.app.hdmi4",
        "icon": "http://15.129.1.98:3000/resources/7fa3f2308e57f431fa0725cd1858ef631012e0d9/HDMI_4.png",
        "modified": false,
        "lastUniqueId": 255,
        "hdmiPlugIn": false,
        "dongleConnected": false,
        "subList": [],
        "subCount": 0,
        "favorite": false
      }
    ]
  }
}
```

**Comment by klattimer** [comment]
@da3dsoul yep, I spotted this was happening... there doesn't seem to be a waiting thread in ws4py not sure why that is, I was expecting it to hold onto a thread and then exit, either way I gone fucked it up when I rewrote it but I rewrote it this way for a reason which wont become entirely apparent for a while, sorry it's such a work in progress :) 

If you want to contribute a small patch for the issue to handle in in the short term I'd be happy to accept it, but as I have a bunch of new features in progress I don't want to take my attention away from those when I next get to it. Unfortunately this is sitting a little on the back burner at the minute while I sort other issues with other projects.

**Comment by da3dsoul** [comment]
Kk I shall
