### ISSUE TITLE
[UJ6309] New device: working, suggestions towards Readme update

### ISSUE THREAD

**Issue by MVogel91** [klattimer/LGWebOSRemote#54]
Thanks a lot for your great work here.

It took me some time to get it up and running, possibly due to changes done to the code and not reflected in the examples (e.g. the devices do not show the necessity of the device name)

I would recommend to update the Readme.md to reflect this, like:

lgtv scan <TV IP address> <Freely chosen device name>
lgtv <device name> off

etc.

**Comment by klattimer** [comment]
It'll get done in due course, there are other things being added at the moment.
