### ISSUE TITLE
Socket Timeout Error When Using Scan Command

### ISSUE THREAD

**Issue by DarkCeptor44** [klattimer/LGWebOSRemote#55]
The command `lgtv scan` is causing a Socket Timeout error almost instantly which makes me think the timeout might be set to one second or less or it's a different cause I don't really know.
Anyway the full error is:

```
Traceback (most recent call last):
  File "H:\Programacao\Python\lgtv-os\lgtv-venv\Scripts\lgtv-script.py", line 11, in <module>
    load_entry_point('LGTV==0.2', 'console_scripts', 'lgtv')()    
  File "h:\programacao\python\lgtv-os\lgtv-venv\lib\site-packages\LGTV\__init__.py", line 109, in main
    results = LGTVScan()
  File "h:\programacao\python\lgtv-os\lgtv-venv\lib\site-packages\LGTV\scan.py", line 25, in LGTVScan
    response, address = sock.recvfrom(512)
socket.timeout: timed out
```

**Comment by besendorf** [comment]
I also have this error. Im on Arch Linux with python3. Does this work with python3? The readme only mentions python2

**Comment by klattimer** [comment]
I think on some system configurations you need to be root to create that socket in the first instance which would cause an instant timeout.

**Comment by besendorf** [comment]
Thats not it:
```
Traceback (most recent call last):
  File "/usr/bin/lgtv", line 11, in <module>
    load_entry_point('LGTV==0.2', 'console_scripts', 'lgtv')()
  File "/usr/lib/python3.8/site-packages/LGTV/__init__.py", line 111, in main
    results = LGTVScan()
  File "/usr/lib/python3.8/site-packages/LGTV/scan.py", line 25, in LGTVScan
    response, address = sock.recvfrom(512)
socket.timeout: timed out
```

**Comment by klattimer** [comment]
Hmm, weird... That shouldn't be timing out.

**Comment by besendorf** [comment]
Can I do something to help debugging?

**Comment by klattimer** [comment]
Doesn't look like it, seems like it's a network handling issue on your system. Maybe look for other people that get that with python on arch? Honestly it's just sending a packet and waiting on a response so no idea... unless you have your system timeout set to zero or something...

**Comment by DarkCeptor44** [comment]
I've found something about the error a while back, for future reference I'm gonna leave it here:

> I tried with 15s of timeout instead of 1 or 2 but all it does is throw the error 15 seconds later rather than instantly.
> 
> From what I've searched because `239.255.255.250` is not accessible from the local machine it's always gonna throw a timeout error, because it's a client socket instead of a server socket.

**Comment by reimerp** [comment]
I was running in the same issue on ubuntu 20.04 running python 3,8,2 _occasionally_. It was gone after running again.

**Comment by klattimer** [comment]
239.255.255.250 is the DNLA broadcast address for SSDP, this should be fine.

**Comment by bkero** [comment]
I was able to replicate this problem as root, so I suspect it is not user-permission related.

**Comment by C0rn3j** [comment]
Same on Arch, 3.8.3, venv or no venv, root or no root. 

Turns out this is due to my TV having port 3000 closed when it's turned off, the script seems to be missing handling for that.

```
[1] % sudo lgtv scan
Traceback (most recent call last):
  File "/home/c0rn3j/lgtv-venv/bin/lgtv", line 11, in <module>
    load_entry_point('LGTV==0.2', 'console_scripts', 'lgtv')()
  File "/home/c0rn3j/lgtv-venv/lib/python3.8/site-packages/LGTV/__init__.py", line 111, in main
    results = LGTVScan()
  File "/home/c0rn3j/lgtv-venv/lib/python3.8/site-packages/LGTV/scan.py", line 25, in LGTVScan
    response, address = sock.recvfrom(512)
socket.timeout: timed out
(lgtv-venv) 
```
Turn TV on...
```
c0rn3j@Luxuria : ~
[1] % sudo lgtv scan
{"result": "ok", "count": 1, "list": [{"uuid": "censored", "model": "UK6200PLA", "address": "192.168.1.41"}]}
```

You can test that the port is open with nmap:
```
nmap -p 3000 192.168.1.41
```

Except now it works sometimes, and sometimes not.

It also turns out that the timeout value in `scan.py` is too low at 1 second.

`sock.settimeout(1)`

Setting it to 10 instead got the command running consistently for me.

**Comment by klattimer** [comment]
You can't scan a turned off TV. 

That's pretty basic.

I've increased the timeout to 10 seconds.

**Comment by DarkCeptor44** [comment]
> You can't scan a turned off TV.
> 
> That's pretty basic.
> 
> I've increased the timeout to 10 seconds.

Unfortunately increasing the timeout isn't a fix for Windows (at least mine), I said it in [this](https://github.com/klattimer/LGWebOSRemote/issues/55#issuecomment-631702419) comment.

**Comment by klattimer** [comment]
@DarkCeptor44 I don't think it will work on windows, try running iproute2 on windows... That isn't going to work. 

I think likely your user account doesn't have the appropriate rights to read from a raw socket, honestly, I'll happily accept a patch but windows support is not even considered.
