### ISSUE TITLE
Getting usage error with auth

### ISSUE THREAD

**Issue by sobertram** [klattimer/LGWebOSRemote#57]
Thank you for doing this.

My system:
Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux (pi3B+)

lgtv scan
{"count": 1, "result": "ok", "list": [{"uuid": "e86da400-8ee2-a745-ef08-ddf01a0ac54b", "address": "192.168.88.250", "model": "UK6300PUE"}]}

lgtv auth 192.168.88.250
**Error: TV name is required for auth**

Not sure what to look at to fix this. The webOS version on the tv is 4.1.4-5726.

Thanks again.

**Comment by DarkCeptor44** [comment]
You have to put the name you want for the TV, so `lgtv auth 192.168.88.250 NameOfTV` is the command you should run.

**Comment by sobertram** [comment]
Thanks. Unfortunately working from home now for a couple of weeks will be able to test the rest of commands once im back in.

**Comment by Habile2019** [comment]
I think the usage needs updating, not obvious that you need the TV name.

**Comment by DarkCeptor44** [comment]
> I think the usage needs updating, not obvious that you need the TV name.

I agree but from what I've seen this repo was abandoned.

**Comment by Habile2019** [comment]
To be honest I was only interested in the message function and luckily that's the only thing that works for me so I can display a message on the TV when my blood sugar needs attention... life is too short I guess but respects to the author as I wouldn't have gotten this far otherwise! Stay safe all!

**Comment by klattimer** [comment]
I ain't had time to work on it, not abandoned but looking for contributors.

**Comment by sobertram** [comment]
Just confirming this worked for me. Thanks @DarkCeptor44
