### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by reimerp** [klattimer/LGWebOSRemote#61]
I assume you are running in a python 3.x environment, since
`python -m venv lgtv-venv` looks 3.x, in 2.x this has to be used: `virtualenv lgtv-venv`

My Environment is Python 3.8.2 in Ubuntu 20.04
the first error occured whille running `pip install git+https://github.com/klattimer/LGWebOSRemote`:

> error: invalid command 'bdist_wheel'

so I added `pip install wheel` just after activating the virtual environment.
I was able to scan and auth, but issiong a swInfo command failed:

>AttributeError: 'str' object has no attribute 'decode'

This issue was already fixed (issue an MR still open) and did work for me.

But I got another error:

> lgtv MyTV swInfo
DEBUG:root:Initiating handshake
DEBUG:root:Received response
DEBUG:root:{"type":"registered","id":"register_0","payload":{"client-key":"b3ed4708d529f0e69f1d6f81f69f2240"}}
DEBUG:root:Handshake complete
DEBUG:root:{'id': 'sw_info_0', 'type': 'request', 'uri': 'ssap://com.webos.service.update/getCurrentSWInformation'}
{"closing": {"code": 1006, "reason": "Going away"}}
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./lgtv-venv/lib/python3.8/site-packages/ws4py/websocket.py", line 528, in run
    if not self.once():
  File "./lgtv-venv/lib/python3.8/site-packages/ws4py/websocket.py", line 410, in once
    if not self.process(self.buf[:requested]):
  File "./lgtv-venv/lib/python3.8/site-packages/ws4py/websocket.py", line 480, in process
    self.received_message(s.message)
  File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 95, in received_message
    self.__waiting_callback(json.loads(str(response)))
  File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 104, in __handshake
    self.__execute()
  File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 115, in __execute
    self.__waitClose()
  File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 118, in __waitClose
    self._th.join(timeout=1)
  File "/usr/lib/python3.8/threading.py", line 1008, in join
    raise RuntimeError("cannot join current thread")

I think there is some auzhentication failure, but I found a rather old installation, in a python 2.7.16 environment, against commit _130e619640cf02d317c914c5884a888b8e9ca399_ which is still working

> $ lgtv swInfo
{"type": "response", "id": "sw_info_0", "payload": {"auth_flag": "N", "minor_ver": "80.50", "country": "DE", "sw_type": "FIRMWARE", "major_ver": "05", "ignore_disable": "N", "eco_info": "01", "model_name": "HE_DTV_W17P_AFADABAA", "config_key": "00", "returnValue": true, "language_code": "de-DE", "device_id": "78:5d:c8:54:21:d4", "product_name": "webOSTV 3.5", "country_group": "EU"}}
{"closing": {"reason": "", "code": 1000}}

unfortunately this version lacks multiple screen support...

**Comment by reimerp** [comment]
I tried running the actual codebase on my 2.7.16 system, where the old code was working.

>  File "/home/pi/lgtv-venv/lib/python2.7/site-packages/LGTV/scan.py", line 3, in <module>
    from urllib.parse import unquote
ImportError: No module named parse

This can be fixed by
```
import socket
import re   
try:
    from urllib.parse import unquote
except ImportError:
     from urlparse import unquote
from time import sleep
```
in scan.py
scan and auth is succesful, but than I ran into the error documented above, now in 2.7 python.

**Comment by klattimer** [comment]
January 2020 saw the end of Python 2 support.

No I will not add support for python 2.7 back in so would rather fix the issue, I'll check the PRs you mentioned but this works for me at the minute.

**Comment by reimerp** [comment]
You misunderstood, I tried to run in 3.8.2 with the problems listen in my first post. I have a running version on 2.7 but with old code. With the HEAD version I am running in the
>RuntimeError: cannot join current thread
issue on 2.7.16 AND 3.8.2.
I think there were some changes on the authentication part, and the "cannot join thread" is just an consequence of this.
I try to bisect the issue....

**Comment by klattimer** [comment]
OK, I don't have time to look at this at the minute but it seems it occurs only when the timeout is reached, which is probably why I don't see it.

**Comment by klattimer** [comment]
I don't think this is an issue anymore, it appears to have come from either a turned off TV or a timeout being reached. Can you retest?

**Comment by accountForIssues** [comment]
I get the same runtime error on running almost every command. Some of them (volume, mute, play/pause) work on the TV but still throw the error on the terminal. Some of them (list apps, swinfo, etc.) do nothing but throw the error.

System: Fedora 32; Python 3.7.7; LG OLED55B9

```
Exception in thread WebSocketClient:
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "./lgtv-venv/lib/python3.8/site-packages/ws4py/websocket.py", line 528, in run
if not self.once():
File "./lgtv-venv/lib/python3.8/site-packages/ws4py/websocket.py", line 410, in once
if not self.process(self.buf[:requested]):
File "./lgtv-venv/lib/python3.8/site-packages/ws4py/websocket.py", line 480, in process
self.received_message(s.message)
File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 95, in received_message
self.__waiting_callback(json.loads(str(response)))
File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 104, in __handshake
self.__execute()
File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 115, in __execute
self.__waitClose()
File "./lgtv-venv/lib/python3.8/site-packages/LGTV/remote.py", line 118, in __waitClose
self._th.join(timeout=1)
File "/usr/lib/python3.8/threading.py", line 1008, in join
raise RuntimeError("cannot join current thread")
```

**Comment by accountForIssues** [comment]
I'm not aware of negative consequences of doing this (and I'm sure it can be done more elegantly) but the following solved the error and gives the right output.

In `remote.py`:

In line 115:
Commenting out `self.__waitClose()` by `#self.__waitClose()`

and in line 87: 
Replacing `"reason": reason` by `"reason": str(reason)`

gives the correct output with {"closing": {"code": 1000, "reason": "b''"}} and no errors.

As mentioned in one of the closed issues, the websocket handling seems to be causing the error.

**Comment by DarkCeptor44** [comment]
You're right it does work, other people have yet to test it but in the meantime I'm gonna make a PR.

**Comment by ptruman** [comment]
Confirming the fix works
(I'm experimenting with a node package as well as this python one)

**Comment by Gustry** [comment]
I got the same issue the comment above : https://github.com/klattimer/LGWebOSRemote/issues/61#issuecomment-640200356

The TV is not turned off and the command works, but the exception is still displayed.
