### ISSUE TITLE
What does this caveat exactly means?

### ISSUE THREAD

**Issue by desegura** [klattimer/LGWebOSRemote#69]
Hi @klattimer  😀

"Caveats: You need to auth with the TV before being able to use the on command as it requires the mac address."

Does it means that I can skip the auth if I know the MAC adress of my SK7900PLA? If so, how do I proceed?

When I send the command:
$ lgtv auth 192.168.1.31 MyTV 
Nothing appears on my screen, also... how do I get "MyTV" name?

Thanks a lot!

**Comment by klattimer** [comment]
You'd need to manually create the config file, there should be an example in the project.
