### ISSUE TITLE
works with "model": "OLED55CXAUA"

### ISSUE THREAD

**Issue by mikec309** [klattimer/LGWebOSRemote#72]
Just to let you know, this works with model. "OLED55CXAUA" The list commands start with lower case l rather than uppercase L.

**Comment by caue-santos** [comment]
With model "43LM6300PSB" too 🚀

**Comment by klattimer** [comment]
> With model "43LM6300PSB" too 🚀

considering you've opened another issue, and commented on this one maybe you should have opened an issue to let me know it works and closed the original one. What you've done here is not very informative and leaves me admin work.

**Comment by mikec309** [comment]
My apologies. All I was trying to do was update your list with another model number.
