### ISSUE TITLE
Get/Set Image settings

### ISSUE THREAD

**Issue by KeyofBlueS** [klattimer/LGWebOSRemote#74]
Hi,
first I want to confirm that this tool is working with 43UN73003LC model.
Is it possible to implement options to get/set the image settings as backlight, brightness, contrast and so on?

Thanks and best regards.

**Comment by SAGV** [comment]
This would be so useful!

**Comment by helgek** [comment]
Hi,

I finally found solution to change e.g. picture presets. Please see my last comment at:

https://community.home-assistant.io/t/lg-webos-change-picture-setting-mode-with-scripts/262915

Regards
Helge

**Comment by SAGV** [comment]
Awesome! Will try to implement similar thingy!

**Comment by helgek** [comment]
Thanks for the implementation! In case you will also do the set pictureMode part I found this info on pictureModes:

https://www.webosose.org/docs/reference/ls2-api/com-webos-service-settings/#dimension

pictureMode | Optional | String | You can use the following values:vivid, normal, eco, cinema, game, sports, expert1, expert2

**Comment by helgek** [comment]
We're discussing here the pictureModes working with our devices:
https://github.com/merdok/homebridge-webos-tv/issues/371

**Comment by caniswim** [comment]
How do I set a value for my TV's backlight using LGWebOSRemote?

Sorry for the question here, but I'm new to the subject and can't find the answer.
