### ISSUE TITLE
Getting List of Requests From LG

### ISSUE THREAD

**Issue by annie-rizvi** [klattimer/LGWebOSRemote#83]
In the remote.py file, you have a list of commands that you send to the LG smart tv to control the TV (on/off, mute, etc.). Where did you get this list of commands? Is there a specific request you can send to the LG smart tv to receive a list of these commands or an official manual where they are listed? I am building a similar remote that needs proper documentation and needs to be easy to alter if LG webOS commands are changed.

**Comment by klattimer** [comment]
I reverse engineered them from the iOS app.
