### ISSUE TITLE
Timeouts on LH615V

### ISSUE THREAD

**Issue by tykus160** [klattimer/LGWebOSRemote#94]
While scan shows LH615V and auth is able to authorize this TV, any other command fails after few seconds. TV details below:
| Key      | Value    |
| -------- | --------:|
| Model    | LH615V   |
| webOS    | 3.0      |
| Firmware | 05.60.10 |

**Comment by klattimer** [comment]
This might be an ssl issue, please check the readme for updated info.

**Comment by tykus160** [comment]
I don't have this TV anymore, so I cannot confirm unfortunately. Good to see this readme though!
